server:
  read_timeout_duration: 10s
  write_timeout_duration: 10s
  idle_timeout_duration: 60s
  read_header_timeout_duration: 10s
  port: :8080
database:
  type: postgres
  host: localhost
  port: 5432
  username: admin
  password: secret123
  name: goauthdb
redis:
  host: localhost
  password:
  port: 6379
